// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ddd-sample/domain/service"
	"ddd-sample/interface/persistence/memory"
	"ddd-sample/interface/transport"
	"ddd-sample/interface/workflow/temporal"
	"ddd-sample/usecase"
)

// Injectors from wire.go:

func InitializeServer() transport.IServer {
	iWorkflowRepo := temporal.NewWorkflowRepository()
	iTicketRepo := memory.NewTicketRepository()
	ticketService := service.NewTicketService(iTicketRepo)
	iTicketUsecase := usecase.NewTicketUseCase(iWorkflowRepo, ticketService, iTicketRepo)
	iServer := transport.NewServer(iTicketUsecase)
	return iServer
}
